add output before align
AsyaPronina/face_recognition_openvino pull request #1
Opened 2019-05-01 15:52 UTC by daryafret

and change font and bbox width

2019-05-03 16:44 UTC, AsyaPronina requested changes

2019-05-03 16:44 UTC, AsyaPronina commented on source/main.cpp
> +		beforeAlignFaces.push_back(detectedFaces[i]);
I think we do not need an additional container for the detected faces and can use just detectedFaces vector, which you have made global

2019-05-03 16:44 UTC, AsyaPronina commented on source/main.cpp
> +std::vector<cv::Mat> beforeAlignFaces;
I think it is extra

2019-05-05 12:44 UTC, daryafret commented
maybe you're right. but I couldn't do it with using only container 'detectedFaces'. I'll try again today

2019-05-05 17:30 UTC, closed without merging